package com.example.roomdataplayaround;

import android.arch.lifecycle.LifecycleOwner;
import android.arch.lifecycle.LiveData;
import android.arch.lifecycle.Observer;
import android.support.annotation.NonNull;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

public class MainActivity extends AppCompatActivity {
    private TextView textViewAmount, textViewDate, textViewUID, textViewCounter;
    private Button buttonAddTransaction, buttonPreviewPrevious, buttonPreviewNext;
    private EditText ediTextAmount;
    private double amount;
    private int counter = 0, tempCounter = 0;

    @Override
    protected void onCreate(Bundle savedInstanceState) {

        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        textViewAmount = findViewById(R.id.textViewAmount);
        textViewDate = findViewById(R.id.textViewDate);
        textViewUID = findViewById(R.id.textViewUID);
        textViewCounter = findViewById(R.id.textViewCounter);

        buttonAddTransaction = findViewById(R.id.buttonAdd);
        buttonPreviewNext = findViewById(R.id.buttonNext);
        buttonPreviewPrevious = findViewById(R.id.buttonPrevious);

        ediTextAmount = findViewById(R.id.editTextInputAmount);

        onClickNext();
        onClickPrevious();

        onClickAdd();
    }


    private void addTransaction() {
        TransactionRepository transactionRepo = new TransactionRepository(getApplicationContext());

        if(!ediTextAmount.getText().toString().trim().isEmpty()){
            amount = Double.parseDouble(ediTextAmount.getText().toString().trim());
            transactionRepo.insertTransaction(amount);
        }
    }


    ///Populating every Transaction with UID 0(Auto_Generate not working)
    public void onClickAdd() {
        buttonAddTransaction.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                addTransaction();
                counter++;
                ediTextAmount.setText("");
            }
        });
    }


    public void onClickNext(){
        buttonPreviewNext.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if(tempCounter > 0 || tempCounter < counter){

                    TransactionRepository transactionRepository = new TransactionRepository(getApplicationContext());
                    LiveData<Transaction> tempTransaction = transactionRepository.getTransaction(tempCounter);
                    //setTextViews(tempTransaction);

                    tempCounter++;
                    textViewCounter.setText(String.valueOf(tempCounter));
                }else{
                    Toast.makeText(MainActivity.this, "Noting to Show", Toast.LENGTH_SHORT).show();
                }
            }
        });
    }

    public void onClickPrevious(){
        buttonPreviewPrevious.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if(tempCounter >= 0){

                    TransactionRepository transactionRepository = new TransactionRepository(getApplicationContext());
                    LiveData<Transaction> tempTransaction
                            = transactionRepository.getTransaction(tempCounter);
                    //setTextViews(tempTransaction);

                    tempCounter--;
                    textViewCounter.setText(String.valueOf(tempCounter));
                }else{
                    Toast.makeText(MainActivity.this, "Noting to Show", Toast.LENGTH_SHORT).show();
                }
            }
        });
    }


    //getting null_pointer exception && uid is not getting AutoGenerated()
    public void setTextViews(LiveData<Transaction> t1){
        try{
            textViewUID.setText(t1.getValue().uid);
            textViewAmount.setText(String.valueOf(t1.getValue().getAmount()));
            textViewDate.setText(t1.getValue().getDate());
        }catch (Exception e){
            Toast.makeText(this, e.getMessage() , Toast.LENGTH_SHORT).show();

        }
    }
}
